version: "3"
services:

    airflow-webserver:
        hostname: airflow
        container_name: airflow
        image: andrejunior/airflow-spark:latest
        restart: always
        networks:
            - flix
        depends_on:
            - postgres
            - minio
            - spark-master
            - spark-worker
        environment:   
            - AIRFLOW__CORE__LOAD_EXAMPLES=False
            - LOAD_EX=n
        volumes:
            - airflow-data:/usr/local/airflow/data
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/requirements.txt:/requirements.txt
            - ./airflow/spark/applications:/usr/local/spark/applications            
            - ./airflow/spark/assets:/usr/local/spark/assets
        ports:
            - "8085:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
        deploy:
          resources:
            limits:
              memory: 1.5G          

    mongo:
        image : mongo:5.0
        hostname: mongodb
        container_name: mongodb
        environment:
            - PUID=1000
            - PGID=1000
            - MONGO_INITDB_ROOT_USERNAME=flix
            - MONGO_INITDB_ROOT_PASSWORD=flix
        volumes:
            - ./mongo:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped
        deploy:
          resources:
            limits:
              memory: 500MB        

    minio:
        hostname: bucket 
        container_name: bucket
        image: 'bitnami/minio:latest'
        environment:
            MINIO_ROOT_USER: flix
            MINIO_ROOT_PASSWORD: flix#Pass#2022
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - minio_data:/data
        networks:
            - flix
        healthcheck:
            test: ["CMD", "curl", "-f", "http://bucket:9000/minio/health/live"]
            interval: 60s
            timeout: 20s
            retries: 3
        deploy:
          resources:
            limits:
              memory: 400MB

    createbuckets:
        image: minio/mc
        networks:
            - flix
        depends_on:
            - minio
        entrypoint: >
            /bin/sh -c "
            /usr/bin/mc config host add myminio http://bucket:9000 flix flix#Pass#2022;
            /usr/bin/mc rm -r --force myminio/flix;
            /usr/bin/mc mb myminio/flix;
            /usr/bin/mc policy download myminio/flix;
            exit 0;
            "
    spark-master:        
        image: bitnami/spark:3.2.1
        # https://docs.bitnami.com/tutorials/work-with-non-root-containers/
        user: root 
        hostname: spark
        container_name: spark
        networks:
            - flix
        environment:
            - SPARK_MODE=master
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:        
            - ./airflow/spark/assets:/usr/local/spark/assets 
        ports:
            - "8081:8080"
            - "7077:7077"
        deploy:
          resources:
            limits:
              memory: 1G

    spark-worker:
        image: bitnami/spark:3.2.1
        user: root
        hostname: spark-worker
        container_name: spark-worker
        networks:
            - flix
        environment:
            - SPARK_MODE=worker
            - SPARK_MASTER_URL=spark://spark:7077
            - SPARK_WORKER_MEMORY=1G
            - SPARK_WORKER_CORES=1
            - SPARK_RPC_AUTHENTICATION_ENABLED=no
            - SPARK_RPC_ENCRYPTION_ENABLED=no
            - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
            - SPARK_SSL_ENABLED=no
        volumes:          
            - ./airflow/spark/assets:/usr/local/spark/assets 
        depends_on:
            - spark-master
        deploy:
          resources:
            limits:
              memory: 1GB

volumes:
    postgres:
    airflow-data:
    minio_data:

networks:
    flix:
        driver: bridge
